### ISSUE TITLE
UICAL-180:  User cannot save edited data in "Exception Period" by selecting "Valid To" equal to "Valid From"

### ISSUE THREAD

**Issue by ncovercash** [ualibweb/ui-calendar#10]
# [UICAL-180 Jira](https://issues.folio.org/projects/UICAL/issues/UICAL-180)

> ### Preconditions:
> 1. Snapshot env is opened
> 2. Calendar app is opened
> 3." Online" service points selected
> 4. "Open calendar to add exceptions" button clicked
> 5. "New: Exception Period" is created (ex. 11/01/2021 - 11/04/2021)
> 6.  Exception Period opened like edit
> 
> ### Steps to Reproduce:
> 
> 1. Select in "Valid To" field "11/01/2021"
> 2. Click on "Save & close" button
> 3. Observe result
> 
> **Expected Results:** User can save edited data "Exception Period" by selecting "Valid To" equal to "Valid From"
> 
> **Actual Results:** User can not save edited data "Exception Period" by selecting "Valid To" equal to "Valid From"
> 
> **Note:** User can save edited data "Exception Period" by selecting "Valid From" equal to  "Valid To", but only in this order?

@librarianmage let me know before you start looking at this; there are some caveats about how this fork is set up in order to be mergeable with upstream.

Depending on what the product owner/manager/etc say, they may slate the fix differently, however, it should hopefully be something that is not too complex!

Cheryl says:
> I had never been able to edit exception periods. However, since they are now editable by choosing the the valid from and valid to dates in that order but not in the order valid to, valid from, I would call this a bug. I think some developer should look at the code history to see if the ability to edit was added deliberately.

It seems like they don't even know if editing was supposed to be a feature, which seems contradictory?  Although I am curious how editing even works at all in the current database spaghetti, I could definitely see it being an accidental "feature" not communicated between the old back/front teams.

Snapshot env they referenced: https://folio-snapshot.dev.folio.org/

[Current API](https://s3.amazonaws.com/foliodocs/api/mod-calendar/calendar.html) does seem to support PUTing/etc with `exceptional` periods, so a good starting point might be seeing if/what requests are even sent.  I really like Charles for web debugging if you're looking for a tool to do this outside of the browser

**Comment by librarianmage** [comment]
Was unable to reproduce; [posted comment](https://issues.folio.org/projects/UICAL/issues/UICAL-180) on JIRA
![Exception-Period-Test](https://user-images.githubusercontent.com/12386291/144483316-c676fe5b-95d8-448b-8ede-172fbca571ba.gif)
